### ISSUE TITLE
Only works on first pane

### ISSUE THREAD

**Issue by bedge** [kuychaco/multirow-tabs#4]
If there are multiple files open in side-by-side panes, the tab wrap only works in one of them:
![screen shot 2015-11-06 at 12 20 14 pm](https://cloud.githubusercontent.com/assets/499317/11007730/d1f9b89e-8480-11e5-82e4-c02180f14d7a.png)
Even if the right pane is selected, the ctrl-alt-m toggles the tab wrap only in the left pane.

Great plugin though, this is huge for those of us with ADD and lots of code.

**Comment by forivall** [comment]
Weird, since [my theme](https://github.com/forivall/adwaita-pro-ui), which has multirow tabs (added before i found out about this package), works fine with tab wrapping, and I can't tell what would do that with this extension.

**Comment by kuychaco** [comment]
Issue resolved for version 0.3.3. Thanks for your comments!
